export const estados = [
  {name: 'Aguascalientes', value: 'AG'},
  {name: 'Baja California', value: 'BC'},
  {name: 'Baja California Sur', value: 'BS'},
  {name: 'Campeche', value: 'CM'},
  {name: 'Chiapas', value: 'CS'},
  {name: 'Chihuahua', value: 'CH'},
  {name: 'Ciudad de México', value: 'CX'},
  {name: 'Coahuila', value: 'CO'},
  {name: 'Colima', value: 'CL'},
  {name: 'Durango', value: 'DG'},
  {name: 'Guanajuato', value: 'GT'},
  {name: 'Guerrero', value: 'GR'},
  {name: 'Hidalgo', value: 'HG'},
  {name: 'Jalisco', value: 'JC'},
  {name: 'México', value: 'EM​'},
  {name: 'Michoacán', value: 'MI'},
  {name: 'Morelos', value: 'MO'},
  {name: 'Nayarit', value: 'NA'},
  {name: 'Nuevo León', value: 'NL'},
  {name: 'Oaxaca', value: 'OA'},
  {name: 'Puebla', value: 'PU'},
  {name: 'Querétaro', value: 'QT'},
  {name: 'Quintana Roo', value: 'QR'},
  {name: 'San Luis Potosí', value: 'SL'},
  {name: 'Sinaloa', value: 'SI'},
  {name: 'Sonora', value: 'SO'},
  {name: 'Tabasco', value: 'TB'},
  {name: 'Tamaulipas', value: 'TM'},
  {name: 'Tlaxcala', value: 'TL'},
  {name: 'Veracruz', value: 'VE'},
  {name: 'Yucatán', value: 'YU'},
  {name: 'Zacatecas', value: 'ZA'}
]