export const estados = [
  {name: 'Aguascalientes', value: 'AS'},
  {name: 'Baja California', value: 'BC'},
  {name: 'Baja California Sur', value: 'BS'},
  {name: 'Campeche', value: 'CC'},
  {name: 'Chiapas', value: 'CS'},
  {name: 'Chihuahua', value: 'CH'},
  {name: 'Ciudad de México', value: 'DF'},
  {name: 'Coahuila', value: 'CL'},
  {name: 'Colima', value: 'CM'},
  {name: 'Durango', value: 'DG'},
  {name: 'Guanajuato', value: 'GT'},
  {name: 'Guerrero', value: 'GR'},
  {name: 'Hidalgo', value: 'HG'},
  {name: 'Jalisco', value: 'JC'},
  {name: 'México', value: 'MC'},
  {name: 'Michoacán', value: 'MN'},
  {name: 'Morelos', value: 'MS'},
  {name: 'Nayarit', value: 'NT'},
  {name: 'Nuevo León', value: 'NL'},
  {name: 'Oaxaca', value: 'OC'},
  {name: 'Puebla', value: 'PL'},
  {name: 'Querétaro', value: 'QT'},
  {name: 'Quintana Roo', value: 'QR'},
  {name: 'San Luis Potosí', value: 'SP'},
  {name: 'Sinaloa', value: 'SL'},
  {name: 'Sonora', value: 'SR'},
  {name: 'Tabasco', value: 'TC'},
  {name: 'Tamaulipas', value: 'TS'},
  {name: 'Tlaxcala', value: 'TL'},
  {name: 'Veracruz', value: 'VZ'},
  {name: 'Yucatán', value: 'YN'},
  {name: 'Zacatecas', value: 'ZS'},
  {name: 'Otro', value: 'NE'}
]
